# Generated by Django 4.2.27 on 2025-12-07 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_alter_deliveryagency_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('DAILY', 'Informe Diario'), ('MONTHLY', 'Informe Mensual')], max_length=20, verbose_name='Tipo de Informe')),
                ('report_date', models.DateField(help_text='Para informes diarios: la fecha específica. Para informes mensuales: primer día del mes', verbose_name='Fecha del Informe')),
                ('status', models.CharField(choices=[('GENERATING', 'Generando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='GENERATING', max_length=20, verbose_name='Estado')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/%Y/%m/', verbose_name='Archivo PDF')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='reports/excel/%Y/%m/', verbose_name='Archivo Excel')),
                ('json_data', models.JSONField(blank=True, help_text='Datos estructurados del informe en formato JSON', null=True, verbose_name='Datos JSON')),
                ('total_packages', models.IntegerField(default=0, verbose_name='Total de Paquetes')),
                ('total_sacas', models.IntegerField(default=0, verbose_name='Total de Sacas')),
                ('total_lotes', models.IntegerField(default=0, verbose_name='Total de Lotes')),
                ('total_individual_packages', models.IntegerField(default=0, help_text='Paquetes enviados sin saca', verbose_name='Total de Paquetes Individuales')),
                ('is_automatic', models.BooleanField(default=False, help_text='True si fue generado automáticamente por una tarea programada', verbose_name='Generación Automática')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
                'db_table': 'report_report',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='Destino')),
                ('package_status', models.CharField(blank=True, max_length=20, verbose_name='Estado de Paquetes')),
                ('packages_count', models.IntegerField(default=0, verbose_name='Cantidad de Paquetes')),
                ('sacas_count', models.IntegerField(default=0, verbose_name='Cantidad de Sacas')),
                ('lotes_count', models.IntegerField(default=0, verbose_name='Cantidad de Lotes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='report.report', verbose_name='Informe')),
                ('transport_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.transportagency', verbose_name='Agencia de Transporte')),
            ],
            options={
                'verbose_name': 'Detalle de Informe',
                'verbose_name_plural': 'Detalles de Informes',
                'db_table': 'report_detail',
                'ordering': ['report', 'transport_agency', 'destination'],
                'indexes': [models.Index(fields=['report', 'transport_agency'], name='report_deta_report__9d06d2_idx'), models.Index(fields=['report', 'destination'], name='report_deta_report__21792b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'report_date'], name='report_repo_report__9226c3_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='report_repo_status_6ffb30_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_automatic', '-report_date'], name='report_repo_is_auto_b5d375_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('report_type', 'report_date')},
        ),
    ]
