# Generated by Django 4.2.27 on 2025-12-08 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Reporte Programado')),
                ('report_type', models.CharField(choices=[('packages', 'Paquetes'), ('statistics', 'Estadísticas'), ('agencies', 'Agencias'), ('destinations', 'Destinos')], max_length=50, verbose_name='Tipo de Reporte')),
                ('frequency', models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('CUSTOM', 'Personalizado')], max_length=20, verbose_name='Frecuencia')),
                ('config', models.JSONField(default=dict, help_text='Filtros, columnas, etc.', verbose_name='Configuración del Reporte')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('next_run', models.DateTimeField(verbose_name='Próxima Ejecución')),
                ('recipients', models.JSONField(default=list, help_text='Lista de emails', verbose_name='Destinatarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Programado',
                'verbose_name_plural': 'Reportes Programados',
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de Configuración')),
                ('report_type', models.CharField(choices=[('packages', 'Paquetes'), ('statistics', 'Estadísticas'), ('agencies', 'Agencias'), ('destinations', 'Destinos'), ('custom', 'Personalizado')], max_length=50, verbose_name='Tipo de Reporte')),
                ('config', models.JSONField(default=dict, help_text='Filtros, columnas, formato, etc.', verbose_name='Configuración JSON')),
                ('is_default', models.BooleanField(default=False, verbose_name='Configuración por Defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
