# Generated by Django 4.2.27 on 2025-12-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportschedule_reportconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('DAILY', 'Informe Diario'), ('DAILY_DISPATCH', 'Informe Diario - Despachos'), ('DAILY_RECEPTION', 'Informe Diario - Recepciones'), ('MONTHLY', 'Informe Mensual')], max_length=30, verbose_name='Tipo de Informe'),
        ),
    ]
