# Generated by Django 5.2.8 on 2025-12-01 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='package_imports/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('successful_imports', models.IntegerField(default=0)),
                ('failed_imports', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Importación de Paquetes',
                'verbose_name_plural': 'Importaciones de Paquetes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_master', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Número Master')),
                ('guide_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número de Guía')),
                ('agency_guide_number', models.CharField(blank=True, help_text='Número de guía asignado por la Agencia de Transporte (si aplica)', max_length=50, verbose_name='Número de Guía de Agencia')),
                ('guide_history', models.TextField(blank=True, help_text='Registro automático de cambios de número de guía', verbose_name='Historial de Guías')),
                ('status_history', models.TextField(blank=True, help_text='Registro automático de cambios de estado con fecha', verbose_name='Historial de Estados')),
                ('notes_history', models.TextField(blank=True, help_text='Registro automático de cambios de notas con fecha', verbose_name='Historial de Notas')),
                ('status', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_BODEGA', 'En Bodega'), ('RETENIDO', 'Retenido'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto')], default='RECIBIDO', max_length=20)),
                ('shipping_type', models.CharField(choices=[('AGENCIA', 'Entrega en Agencia'), ('DOMICILIO', 'Entrega a Domicilio'), ('MULTIPLE', 'Dividir en Múltiples Envíos')], default='AGENCIA', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='packages.package')),
                ('pull', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='logistics.pull')),
                ('transport_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages_by_agency', to='catalog.transportagency', verbose_name='Agencia de Transporte')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='packages_pa_status_d99ada_idx'), models.Index(fields=['transport_agency', '-created_at'], name='packages_pa_transpo_b13f69_idx'), models.Index(fields=['pull', '-created_at'], name='packages_pa_pull_id_81958c_idx')],
            },
        ),
    ]
