# Generated by Django 5.2.8 on 2025-12-03 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_deliveryagency'),
        ('logistics', '0002_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivery_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages_delivered', to='catalog.deliveryagency', verbose_name='Agencia de Reparto'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['delivery_agency', '-created_at'], name='packages_pa_deliver_88a69f_idx'),
        ),
    ]
