# Generated by Django 5.2.8 on 2025-12-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_deliveryagency_options_and_more'),
        ('logistics', '0008_remove_pull_description'),
        ('packages', '0002_package_delivery_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='hashtags',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por espacios (ej: #urgente #fragil #express)', max_length=500, verbose_name='Hashtags'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['hashtags'], name='packages_pa_hashtag_8a7493_idx'),
        ),
    ]
