# Generated by Django 5.2.8 on 2025-12-03 08:18

from django.db import migrations, models


def update_recibido_to_no_receptado(apps, schema_editor):
    """Cambiar todos los paquetes con estado RECIBIDO a NO_RECEPTADO"""
    Package = apps.get_model('packages', 'Package')
    Package.objects.filter(status='RECIBIDO').update(status='NO_RECEPTADO')


def reverse_update(apps, schema_editor):
    """Revertir cambios si es necesario"""
    Package = apps.get_model('packages', 'Package')
    Package.objects.filter(status='NO_RECEPTADO').update(status='RECIBIDO')


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_hashtags_and_more'),
    ]

    operations = [
        # Primero ejecutar la migración de datos
        migrations.RunPython(update_recibido_to_no_receptado, reverse_update),
        # Luego modificar el campo con el nuevo default
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('NO_RECEPTADO', 'No Receptado'), ('EN_BODEGA', 'En Bodega'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto'), ('RETENIDO', 'Retenido')], default='NO_RECEPTADO', max_length=20),
        ),
    ]
