# Generated by Django 5.2.8 on 2025-12-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_package_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='shipping_type',
        ),
    ]
