# Generated by Django 4.2.27 on 2025-12-08 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0005_remove_shipping_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('NO_RECEPTADO', 'No Receptado'), ('EN_BODEGA', 'En Bodega'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto'), ('RETENIDO', 'Retenido')], max_length=20, verbose_name='Estado Anterior')),
                ('new_status', models.CharField(choices=[('NO_RECEPTADO', 'No Receptado'), ('EN_BODEGA', 'En Bodega'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto'), ('RETENIDO', 'Retenido')], max_length=20, verbose_name='Estado Nuevo')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Cambio')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='packages.package', verbose_name='Paquete')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'db_table': 'packages_status_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['package', 'changed_at'], name='packages_st_package_586a73_idx'), models.Index(fields=['old_status', 'new_status', 'changed_at'], name='packages_st_old_sta_e65231_idx')],
            },
        ),
    ]
