# Generated by Django 4.2.27 on 2025-12-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='export_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuracion de columnas para exportacion de paquetes'),
        ),
    ]
