# Generated by Django 5.2.8 on 2025-12-01 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispatch_date', models.DateField(db_index=True, verbose_name='Fecha de Despacho')),
                ('status', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_CURSO', 'En Curso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PLANIFICADO', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'db_table': 'dispatch_dispatch',
                'ordering': ['-dispatch_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pull',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='pull_barcodes/', verbose_name='Código de Barras')),
                ('common_destiny', models.CharField(max_length=200, verbose_name='Destino Común')),
                ('size', models.CharField(choices=[('PEQUENO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], max_length=10, verbose_name='Tamaño')),
                ('priority', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('guide_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Guía')),
            ],
            options={
                'verbose_name': 'Pull (Saca)',
                'verbose_name_plural': 'Pulls (Sacas)',
                'db_table': 'dispatch_pull',
                'ordering': ['-created_at'],
            },
        ),
    ]
