# Generated by Django 5.2.8 on 2025-12-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('logistics', '0001_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='dispatches', to='packages.package', verbose_name='Paquetes Individuales'),
        ),
        migrations.AddField(
            model_name='pull',
            name='transport_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pulls', to='catalog.transportagency', verbose_name='Agencia de Transporte'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='pulls',
            field=models.ManyToManyField(blank=True, related_name='dispatches', to='logistics.pull', verbose_name='Sacas Asociadas'),
        ),
        migrations.AddIndex(
            model_name='pull',
            index=models.Index(fields=['status', '-created_at'], name='dispatch_pu_status_e1b447_idx'),
        ),
        migrations.AddIndex(
            model_name='pull',
            index=models.Index(fields=['priority', '-created_at'], name='dispatch_pu_priorit_6ddd3e_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['dispatch_date', 'status'], name='dispatch_di_dispatc_9fb609_idx'),
        ),
    ]
