# Generated by Django 5.2.8 on 2025-12-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pull',
            name='dispatch_pu_status_e1b447_idx',
        ),
        migrations.RemoveIndex(
            model_name='pull',
            name='dispatch_pu_priorit_6ddd3e_idx',
        ),
        migrations.RemoveField(
            model_name='pull',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='pull',
            name='status',
        ),
    ]
