# Generated by Django 5.2.8 on 2025-12-03 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_transportagency_agency_type_and_more'),
        ('logistics', '0003_remove_pull_dispatch_pu_status_e1b447_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='ID de Lote')),
                ('destiny', models.CharField(max_length=200, verbose_name='Destino Común')),
                ('guide_base', models.CharField(blank=True, max_length=50, verbose_name='Base de Guía')),
                ('size', models.CharField(choices=[('PEQUENO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], max_length=10, verbose_name='Tamaño')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='catalog.transportagency', verbose_name='Agencia de Transporte')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'dispatch_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pull',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pulls', to='logistics.batch', verbose_name='Lote'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['destiny'], name='dispatch_ba_destiny_f8ad94_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['transport_agency'], name='dispatch_ba_transpo_2a9ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['created_at'], name='dispatch_ba_created_180d0c_idx'),
        ),
    ]
