# Generated by Django 5.2.8 on 2025-12-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_batch_pull_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='size',
        ),
    ]
