# Generated by Django 5.2.8 on 2025-12-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_remove_batch_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, verbose_name='ID de Lote'),
        ),
    ]
