# Generated by Django 5.2.8 on 2025-12-03 05:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_alter_batch_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_id',
        ),
        migrations.AddField(
            model_name='batch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
