# Generated by Django 5.2.8 on 2025-12-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_remove_batch_batch_id_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pull',
            name='description',
        ),
    ]
