# Generated by Django 4.2.27 on 2025-12-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_remove_pull_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='guide_number',
            field=models.CharField(blank=True, help_text='Número de guía común para todas las sacas del lote', max_length=50, verbose_name='Número de Guía del Lote'),
        ),
    ]
