# Generated by Django 4.2.27 on 2025-12-08 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_batch_guide_number'),
    ]

    operations = [
        # Remover el campo batch antiguo (VARCHAR FK)
        migrations.RemoveField(
            model_name='pull',
            name='batch',
        ),
        # Agregar el campo batch nuevo (UUID FK)
        migrations.AddField(
            model_name='pull',
            name='batch',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='pulls',
                to='logistics.batch',
                verbose_name='Lote'
            ),
        ),
    ]
