# Generated by Django 4.2.27 on 2025-12-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_fix_pull_batch_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='guide_base',
        ),
    ]
