# Generated by Django 5.2.8 on 2025-12-01 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100, unique=True, verbose_name='Ciudad')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia/Departamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'dispatch_location',
                'ordering': ['province', 'city'],
                'unique_together': {('city', 'province')},
            },
        ),
        migrations.CreateModel(
            name='TransportAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('agency_type', models.CharField(choices=[('CARGA_COMPLETA', 'Carga Completa'), ('ENCOMIENDA', 'Encomienda'), ('DOMICILIO', 'Envío a Domicilio'), ('EXPRESS', 'Express'), ('MIXTO', 'Mixto')], default='MIXTO', max_length=20, verbose_name='Tipo de Agencia')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('date_registration', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('coverage', models.ManyToManyField(blank=True, related_name='transport_agencies', to='catalog.location', verbose_name='Cobertura')),
            ],
            options={
                'verbose_name': 'Agencia de Transporte',
                'verbose_name_plural': 'Agencias de Transporte',
                'db_table': 'dispatch_transportagency',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active', 'name'], name='dispatch_tr_active_d4ce7c_idx')],
            },
        ),
    ]
