# Generated by Django 5.2.8 on 2025-12-03 02:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Agencia')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Persona de Contacto')),
                ('coverage_zones', models.TextField(blank=True, help_text='Sectores o zonas que cubre dentro de la ciudad (separadas por comas)', verbose_name='Zonas de Cobertura')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Agencia de Reparto',
                'verbose_name_plural': 'Agencias de Reparto',
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city', 'active'], name='catalog_del_city_fc2ca9_idx'), models.Index(fields=['active', 'name'], name='catalog_del_active_9f1dce_idx')],
            },
        ),
    ]
