# Generated by Django 5.2.8 on 2025-12-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_deliveryagency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportagency',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='transportagency',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Agencia'),
        ),
    ]
