# Generated by Django 5.2.8 on 2025-12-03 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_transportagency_city_alter_transportagency_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportagency',
            name='coverage',
        ),
    ]
