# Generated by Django 5.2.8 on 2025-12-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_transportagency_coverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportagency',
            name='agency_type',
        ),
        migrations.RemoveField(
            model_name='transportagency',
            name='city',
        ),
    ]
