# Generated by Django 5.2.8 on 2025-12-03 07:15

import django.db.models.deletion
from django.db import migrations, models


def migrate_city_to_location(apps, schema_editor):
    """
    Migrar datos de city a location.
    Crea ubicaciones basadas en las ciudades existentes y las asigna.
    """
    DeliveryAgency = apps.get_model('catalog', 'DeliveryAgency')
    Location = apps.get_model('catalog', 'Location')
    
    # Obtener todas las ciudades únicas de las agencias
    agencies = DeliveryAgency.objects.all()
    
    for agency in agencies:
        if agency.city:
            # Buscar o crear la ubicación
            location, created = Location.objects.get_or_create(
                city=agency.city.upper(),
                defaults={'province': 'NO ESPECIFICADO'}
            )
            # Asignar temporalmente el location_id
            agency.location_temp = location.id
            agency.save(update_fields=['location_temp'])


def reverse_migrate(apps, schema_editor):
    """
    Revertir: copiar location.city de vuelta a city
    """
    DeliveryAgency = apps.get_model('catalog', 'DeliveryAgency')
    Location = apps.get_model('catalog', 'Location')
    
    agencies = DeliveryAgency.objects.select_related('location').all()
    for agency in agencies:
        if hasattr(agency, 'location') and agency.location:
            agency.city = agency.location.city
            agency.save(update_fields=['city'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_transportagency_agency_type_and_more'),
    ]

    operations = [
        # Paso 1: Agregar campo temporal para location
        migrations.AddField(
            model_name='deliveryagency',
            name='location_temp',
            field=models.UUIDField(null=True, blank=True),
        ),
        
        # Paso 2: Migrar datos
        migrations.RunPython(migrate_city_to_location, reverse_migrate),
        
        # Paso 3: Eliminar campos antiguos y índices
        migrations.RemoveIndex(
            model_name='deliveryagency',
            name='catalog_del_city_fc2ca9_idx',
        ),
        migrations.RemoveField(
            model_name='deliveryagency',
            name='coverage_zones',
        ),
        migrations.RemoveField(
            model_name='deliveryagency',
            name='notes',
        ),
        
        # Paso 4: Agregar el campo real de location
        migrations.AddField(
            model_name='deliveryagency',
            name='location',
            field=models.ForeignKey(
                null=True, 
                blank=True,
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='delivery_agencies', 
                to='catalog.location', 
                verbose_name='Ubicación'
            ),
        ),
        
        # Paso 5: Copiar datos de location_temp a location
        migrations.RunSQL(
            sql='UPDATE catalog_deliveryagency SET location_id = location_temp WHERE location_temp IS NOT NULL',
            reverse_sql='UPDATE catalog_deliveryagency SET location_temp = location_id WHERE location_id IS NOT NULL'
        ),
        
        # Paso 6: Hacer location NOT NULL
        migrations.AlterField(
            model_name='deliveryagency',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='delivery_agencies', 
                to='catalog.location', 
                verbose_name='Ubicación'
            ),
        ),
        
        # Paso 7: Eliminar campo temporal y city
        migrations.RemoveField(
            model_name='deliveryagency',
            name='location_temp',
        ),
        migrations.RemoveField(
            model_name='deliveryagency',
            name='city',
        ),
        
        # Paso 8: Actualizar opciones del modelo
        migrations.AlterModelOptions(
            name='deliveryagency',
            options={'ordering': ['location__city', 'name'], 'verbose_name': 'Agencia de Reparto', 'verbose_name_plural': 'Agencias de Reparto'},
        ),
        
        # Paso 9: Agregar nuevo índice
        migrations.AddIndex(
            model_name='deliveryagency',
            index=models.Index(fields=['location', 'active'], name='catalog_del_locatio_55ead4_idx'),
        ),
    ]
