# Generated by Django 4.2.27 on 2025-12-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_deliveryagency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportagency',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='transportagency',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Persona de Contacto'),
        ),
        migrations.AddField(
            model_name='transportagency',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='transportagency',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='transportagency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
    ]
